### ISSUE TITLE
Errors occur when used with Botania(Fabirc)

### ISSUE THREAD

**Issue by Q2297045667** [StevePlayzz/Skinned-Lanterns-Fabric#12]
https://paste.ubuntu.com/p/6skJv6FPd2/

**Comment by Steven-Baez** [comment]
hi could you describe the error for me?

**Comment by Q2297045667** [comment]
> hi could you describe the error for me?

Botania version 1.18.1-427
https://www.curseforge.com/minecraft/mc-mods/botania-fabric

skinnedlanterns version1.2.0+build.12
The following error will occur when used with Botania

[22:35:55] [Worker-Main-22/ERROR]: Parsing error loading recipe skinnedlanterns:tiny_potato_lantern_block
com.google.gson.JsonSyntaxException: Unknown item 'skinnedlanterns:lil_tater_lantern_block'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:90) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
[22:35:55] [Worker-Main-22/ERROR]: Parsing error loading recipe skinnedlanterns:tiny_potato_soul_lantern_block
com.google.gson.JsonSyntaxException: Unknown item 'skinnedlanterns:lil_tater_soul_lantern_block'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:90) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[22:35:55] [Worker-Main-22/WARN]: Tried to read an ingredient of unknown type farmersdelight:tool.
